### ISSUE TITLE
apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#112]
Install using "apt-get install" for DEB based systems

apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

**Comment by shamusx** [comment]
note to self for GCP `jumpbox.userdata`:
 **need to test**
```yaml
packages:
  - google-cloud-sdk-gke-gcloud-auth-plugin
apt:
  sources:
    google-cloud-sdk.list:
      source: "deb https://packages.cloud.google.com/apt cloud-sdk main"
write_files:
  - path: /etc/environment
    content: |
      USE_GKE_GCLOUD_AUTH_PLUGIN=True
bootcmd:
  - 'curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -'
```
