### ISSUE TITLE
1.6 meshObservability:

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#165]
add to CP and MP

```
  spec:
    meshObservability:
      settings:
        apiEndpointMetricsEnabled: true
```
