### ISSUE TITLE
switch to `isolationboundaries` by default

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#175]
we also need to update the overlay below...
```     
istio:
      kubeSpec:
        overlays:
          - apiVersion: install.istio.io/v1alpha1
            kind: IstioOperator
            name: tsb-istiocontrolplane
            patches:
              - path: spec.meshConfig.defaultConfig.holdApplicationUntilProxyStarts
                value: true

```
