### ISSUE TITLE
Disconnect gitops from the main branch

### ISSUE THREAD

**Issue by nacx** [tetrateio/tetrate-service-bridge-sandbox#177]
Having gitops in the main branch is a bit inconvenient, as demos that use gitops will end up messing the main git tree.

As an alternative, we could probably better configure gitops to rely on custom branches, or even custom forks, to better disconnect custom temporal tweaks from the main repo. This could be something configurable, defaulting to a `demo-configs` branch, but still allow the ArgoCD module to configure a fork+branch as an alternative.

**Comment by smarunich** [comment]
I am working on re-factoring `argocd`, i will keep you posted. The goal is to expose the variables to allow to map the "user-defined" applications to the target clusters.

Envision something like this:

```yaml
    "argocd_applications": {
        "properties": { "url": ""},
        "tsb": {
        },
        "bookinfo": [
            {
                "cloud": "gcp",
                "cluster_id": 0
            },
            {
              "cloud": "gcp",
              "cluster_id": 1
          }
        ],
        "eshop": [
            {
                "cloud": "azure",
                "cluster_id": 0
            },
            {
              "cloud": "azure",
              "cluster_id": 1
          }
        ]
    }
```
