### ISSUE TITLE
add `wasm` example and `enableWasmDownloadProxy`

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#284]

**Comment by smarunich** [comment]
plus 

```
    spec:
      components:
        istio:
          mountInternalWasmExtensions: true
```
