### ISSUE TITLE
populate region in the clusters list

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#29]

**Comment by smarunich** [comment]
```
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  name: cotivitidemo-eks-1
  organization: tetrate
spec:
  locality:
    region: "eu-west-1"
  tokenTtl: "8760h"
  tier1Cluster: false
```
locality... field
